### ISSUE TITLE
property 'textLabel' not found on object of type 'RNSnackBarView *'  property 'actionButton' not found on object of type 'RNSnackBarView *';

### ISSUE THREAD

**Issue by jbagaresgaray** [cooperka/react-native-snackbar#201] opened 2023-05-26 17:47 UTC
Issue still happening on Expo 48 using react-native-snackbar@2.7.1

property 'textLabel' not found on object of type 'RNSnackBarView *';
property 'actionButton' not found on object of type 'RNSnackBarView *';

![image](https://github.com/cooperka/react-native-snackbar/assets/3625802/28c637a5-88e0-41e6-bb5a-35b3d07016f1)

![image](https://github.com/cooperka/react-native-snackbar/assets/3625802/9286ee8f-0682-497c-8b78-7879134d9122)

**Comment by cooperka** [comment] 2023-05-26 18:53
thanks @jbagaresgaray, closing as duplicate of #200.

**Closed as completed by cooperka** 2023-05-26 18:53 UTC
