### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference

### ISSUE THREAD

**Issue by mdzebardast** [cooperka/react-native-snackbar#99] opened 2018-12-09 10:52 UTC
Hi,
I have a problem with snackbar,

FATAL EXCEPTION: mqt_native_modules
Process: com.oamobile, PID: 11245
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:136)
	at com.azendoo.reactnativesnackbar.SnackbarModule.displaySnackbar(SnackbarModule.java:91)
	at com.azendoo.reactnativesnackbar.SnackbarModule.show(SnackbarModule.java:67)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:164)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:764)

**Comment by cooperka** [comment] 2018-12-09 21:04
Hi @mdzebardast, this looks like a duplicate of https://github.com/cooperka/react-native-snackbar/issues/93 which was recently fixed, can you make sure you're on the latest version?

**Comment by mdzebardast** [comment] 2018-12-10 08:21
Thanks @cooperka, I've checked the version and it's 0.4.6. I would update it and test it on Android 8.

**Comment by cooperka** [comment] 2018-12-11 15:59
Great. Closing for now, if you still have issues feel free to comment and I can re-open.

**Closed as completed by cooperka** 2018-12-11 15:59 UTC
Labels: duplicate
