### ISSUE TITLE
Calling setstate doesn't show snackbar.

### ISSUE THREAD

**Issue by kundan1301** [cooperka/react-native-snackbar#81] opened 2018-06-19 17:14 UTC
Calling setstate doesn't show snackbar.
```
this.setState({ loading: true });  
const res = await Utils.verifyOtp(code);  
this.setState({ loading: false});  
Snackbar.show({title:message,duration:duration,backgroundColor:backGroundColor});
```
Above code doesn't show snackbar. But Below code show snackbar
```
//this.setState({ loading: true });  
const res = await Utils.verifyOtp(code);  
//this.setState({ loading: false});  
Snackbar.show({title:message,duration:duration,backgroundColor:backGroundColor});
```

**Comment by kundan1301** [comment] 2018-06-20 09:35
This works as well
```
setTimeout(()=>{
  Snackbar.show({title:message,duration:duration,backgroundColor:backGroundColor});
}, 10)
```

**Comment by cooperka** [comment] 2018-06-20 16:02
Hi @kundan1301, that's very strange. Are there any routes or screens that are added or removed based on the state (such as a modal that pops up)?

If you could link to a working example app that would help me diagnose the issue. Feel free to fork and edit the [official example app](https://github.com/cooperka/react-native-snackbar/tree/master/example) if that's easier.

**Comment by kundan1301** [comment] 2018-06-21 06:10
Hello @cooperka, Yes I am adding a modal to show loader.  Once network call is completed `const res = await Utils.verifyOtp(code);   // this is network call
`, I am trying to show error or success in snackbar.

**Comment by cooperka** [comment] 2018-06-29 01:37
Unfortunately, that won't currently work -- see https://github.com/cooperka/react-native-snackbar/issues/28 for details.

The snackbar attaches itself to the top screen, and if that screen is a modal, the snackbar will go away along with the modal. Whether this Android behavior is a "bug" or a "feature" depends on who you ask 😉 

For now, you could either show the loading indicator using something other than a modal, or you could add a slight delay (as you suggested) to make sure the snackbar attaches to the screen below the modal.

**Comment by cooperka** [comment] 2018-06-29 01:38
Closing as duplicate of #28; feel free to reply on either issue if you have any questions. Thanks!

**Closed as completed** 2018-06-29 01:37 UTC
Labels: duplicate, troubleshooting
